Implement a new Variant type for rejection sampling
tensorzero/tensorzero pull request #329
Opened 2024-09-17 02:42 UTC by virajmehta

There could still be many more integration tests written but I think this is in fairly good shape and worth looking at. Happy to write more / make changes as needed. When we merge, this will close #287

2024-09-17 16:33 UTC, GabrielBianconi commented on gateway/src/variant/rejection_sampling.rs
> +async fn inner_select_best_candidate<'a, 'request>(
Document implementation and return type better.

2024-09-17 16:33 UTC, GabrielBianconi commented on gateway/src/variant/rejection_sampling.rs
> +impl EvaluatorConfig {
Document functions

2024-09-17 16:36 UTC, GabrielBianconi commented on gateway/src/variant/mod.rs
> +    RejectionSampling(rejection_sampling::RejectionSamplingConfig),
serde rename to `experimental_rejection_sampling`

2024-09-17 18:22 UTC, virajmehta commented
TODO: change the name to best-of-n sampling

2024-09-18 20:11 UTC, GabrielBianconi approved these changes
Almost there. Let's merge pending empirical validation.

2024-09-18 20:11 UTC, GabrielBianconi commented on gateway/src/variant/best_of_n.rs
> +/// If a model inference actually occurs, we return None and the model inference result instead of Err() so
`If an issue occurs but a model inference...`

2024-09-18 20:24 UTC, virajmehta commented on gateway/src/variant/best_of_n.rs
> +        return Ok((None, model_inference_result));
log all failures here

2024-09-22 20:58 UTC, GabrielBianconi requested changes
almost there

2024-09-22 20:58 UTC, GabrielBianconi commented on examples/gsm8k-custom-recipe-dspy/gsm8k_dspy.ipynb
> +    "        print(\"response is None\")\n",
.

2024-09-22 20:58 UTC, GabrielBianconi commented on examples/gsm8k-custom-recipe-dspy/gsm8k_dspy.ipynb
> +    "\n",
should report success rate

2024-09-22 20:58 UTC, GabrielBianconi commented on gateway/src/variant/best_of_n.rs
> +    let (inference_request, skipped_indices) = evaluator.prepare_request(
If there is a single candidate, we can skip the evaluator.

2024-09-22 20:58 UTC, GabrielBianconi commented on gateway/tests/e2e/best_of_n.rs
> +        "input":{
space

2024-09-22 20:58 UTC, GabrielBianconi commented on gateway/tests/e2e/best_of_n.rs
> +                    "content": "What's the first word in the typical output of ones first program. Answer as a json object with a single field 'answer' containing the string."
one's

2024-09-23 14:52 UTC, GabrielBianconi approved these changes

2024-09-23 15:03 UTC, merged