Add Typescript bindings for minijinja
tensorzero/tensorzero pull request #425
Opened 2024-11-04 19:35 UTC by virajmehta

2024-11-05 19:14 UTC, GabrielBianconi requested changes
```
$  npm test -- --run



> test
> vitest --run


 RUN  v2.1.4 /Users/gabrielbianconi/Development/tensorzero/tmp/tensorzero/dashboard

 ❯ utils/minijinja.test.ts (0)

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  utils/minijinja.test.ts [ utils/minijinja.test.ts ]
Error: Failed to load url ./minijinja/pkg (resolved id: ./minijinja/pkg) in /Users/gabrielbianconi/Development/tensorzero/tmp/tensorzero/dashboard/utils/minijinja.test.ts. Does the file exist?
 ❯ loadAndTransform node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:51920:17

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

 Test Files  1 failed (1)
      Tests  no tests
   Start at  14:11:04
   Duration  240ms (transform 20ms, setup 0ms, collect 0ms, tests 0ms, environment 0ms, prepare 65ms)
```

Failed to reproduce, called the above after `cargo build`. Needs instructions (incl. `cargo install wasm-pack`).

Needs CI.

2024-11-05 19:14 UTC, GabrielBianconi commented on dashboard/package.json
> +    "test": "vitest",
Same as other PR

2024-11-05 19:14 UTC, GabrielBianconi commented on dashboard/utils/minijinja/README.md
> +Run `wasm-pack test --node` from this directory.
Needs to go in CI

2024-11-06 18:11 UTC, virajmehta commented on dashboard/utils/minijinja/Cargo.toml
> +console_error_panic_hook = { version = "0.1.6", optional = true }
I made the default in the crate not use this feature so it should not be compiled by default

2024-11-06 20:40 UTC, GabrielBianconi approved these changes

2024-11-06 20:50 UTC, merged