Configurable credentials
tensorzero/tensorzero pull request #477
Opened 2024-11-21 19:31 UTC by virajmehta

Closes #450, #448

2024-11-21 23:00 UTC, GabrielBianconi requested changes
Run every example in `examples/providers/` as a sanity check

2024-11-21 23:33 UTC, virajmehta commented on gateway/tests/e2e/tensorzero.toml
> +credential_location = "env::GCP_VERTEX_CREDENTIALS_PATH"
not gonna fix this because file:: as default is super challenging for running the binary locally

2024-11-21 23:33 UTC, virajmehta commented on gateway/tests/e2e/tensorzero.toml
> +credential_location = "env::GCP_VERTEX_CREDENTIALS_PATH"
I changed default to env::

2024-11-22 00:01 UTC, virajmehta commented
tested each provider config locally also

2024-11-22 06:21 UTC, GabrielBianconi approved these changes

2024-11-22 22:13 UTC, merged