Batch polling
tensorzero/tensorzero pull request #508
Opened 2024-12-09 16:09 UTC by virajmehta

contains the commits from #491

2024-12-12 15:11 UTC, GabrielBianconi requested changes
Rebasing hell

2025-01-04 19:14 UTC, virajmehta commented
This pull request implements the polling functionality required for TensorZero to support batch inference. Currently we only support OpenAI but there is now a pattern established for a provider-agnostic start batch and poll batch interface that should work with Anthropic and other providers as well.

To do this we added a number of e2e tests, as well as new endpoints and the OpenAI implementation.

2025-01-05 16:16 UTC, GabrielBianconi requested changes
Partial review

2025-01-05 16:16 UTC, GabrielBianconi commented on gateway/src/clickhouse_migration_manager/migrations/migration_0008.rs
> +            MODIFY COLUMN errors Array(String);"#;
🚨

This will convert data like:

```
["('123e4567-e89b-12d3-a456-426614174000','value1')","('987fcdeb-51a2-3c4b-9876-543210987654','value2')"]
```

2025-01-05 16:16 UTC, GabrielBianconi commented on gateway/src/clickhouse_migration_manager/migrations/migration_0008.rs
> +            DROP COLUMN raw_response;\n\
Not correct

2025-01-05 16:16 UTC, GabrielBianconi commented on gateway/tests/e2e/common.rs
> +pub async fn select_feedback_clickhouse(
Only used in one file, move it to the correct location and remove this

2025-01-05 16:16 UTC, GabrielBianconi commented on gateway/tests/e2e/common.rs
> +// Can't figure out why this is dead code
slop

2025-01-05 17:33 UTC, GabrielBianconi commented on gateway/tests/e2e/providers/batch.rs
> +        #[cfg(feature = "batch_tests")]
Just put this top of file?

2025-01-05 17:35 UTC, GabrielBianconi requested changes
Let's add a minimal guide-like example in Python (`examples/guides/batch-inference`).

2025-01-09 21:15 UTC, GabrielBianconi approved these changes
See my changes.

2025-01-09 21:48 UTC, GabrielBianconi submitted a review, later dismissed

2025-01-09 22:47 UTC, GabrielBianconi submitted a review, later dismissed

2025-01-09 23:34 UTC, GabrielBianconi approved these changes

2025-01-10 17:31 UTC, GabrielBianconi approved these changes

2025-01-10 17:45 UTC, merged