Clean up requirements and expand developer guide
tensorzero/tensorzero pull request #615
Opened 2024-12-26 19:05 UTC by GabrielBianconi

2024-12-26 20:56 UTC, GabrielBianconi commented on .github/workflows/general.yml
> -        run: npm test
We don't want API calls in this file

2024-12-27 00:29 UTC, virajmehta requested changes
put the npm tests back for now, couple comments otherwise that aren't hard requirements to merge

2024-12-27 00:29 UTC, virajmehta commented on DEVELOPER_GUIDE.md
>  > **This guide is for developers planning to contribute to TensorZero, not for developers planning to use TensorZero.**
or add to CONTRIBUTING.md with a table of contents? or at minimum link to it from CONTRIBUTING.md?

2024-12-27 16:55 UTC, GabrielBianconi commented on DEVELOPER_GUIDE.md
>  > **This guide is for developers planning to contribute to TensorZero, not for developers planning to use TensorZero.**
merged

2024-12-28 12:36 UTC, virajmehta approved these changes
LGTM!

2024-12-28 12:47 UTC, merged