added a migration for InferenceByEpisode table
tensorzero/tensorzero pull request #652
Opened 2024-12-28 22:47 UTC by virajmehta

2024-12-29 22:08 UTC, virajmehta commented on gateway/src/clickhouse_migration_manager/migrations/migration_0007.rs
> +                function_type Enum8('chat' = 1, 'json' = 2),
passes `rustfmt` so I assume this is wrong

2024-12-29 23:59 UTC, GabrielBianconi requested changes
Minor naming change for clarity.

2024-12-29 23:59 UTC, GabrielBianconi commented on gateway/src/clickhouse_migration_manager/migrations/migration_0007.rs
> +            CREATE TABLE IF NOT EXISTS InferenceByEpisode
`InferenceByEpisodeId` & similar changes throughout

2024-12-30 00:00 UTC, virajmehta commented on gateway/src/clickhouse_migration_manager/migrations/migration_0007.rs
> +            CREATE TABLE IF NOT EXISTS InferenceByEpisode
kk will do

2024-12-30 00:29 UTC, GabrielBianconi approved these changes

2024-12-30 00:40 UTC, merged