Add validations for episode id in feedback api.
tensorzero/tensorzero pull request #698
Opened 2024-12-31 04:03 UTC by hk1997

Issue: https://github.com/tensorzero/tensorzero/issues/350

2024-12-31 22:12 UTC, virajmehta requested changes
Generally looks good! Do you mind adding a test case for the boolean case? I noticed there's no episode-level feedback for it.

2025-01-01 15:26 UTC, hk1997 commented
Hi Viraj,
Happy New Year!

We do have an e2e for episode-level feedback on boolean, see lines: 868-907.

2025-01-01 15:29 UTC, virajmehta commented
> Hi Viraj, Happy New Year!
> 
> We do have an e2e for episode-level feedback on boolean, see lines: 868-907.

you're right, I missed that. This looks good to me!

2025-01-01 15:30 UTC, virajmehta approved these changes
LGTM!

2025-01-02 00:26 UTC, merged

2025-07-08 23:38 UTC, GabrielBianconi commented
recheck

2025-07-08 23:48 UTC, GabrielBianconi commented
Hi @hk1997 - we recently started cleaning up our open-source license/CLA. Could you please comment the following in this PR?

```
I have read the Contributor License Agreement (CLA) and hereby sign the CLA.
```